// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package looprpc // import "github.com/lightninglabs/loop/looprpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerUnchargeSwapRequest struct {
	ReceiverKey          []byte   `protobuf:"bytes,1,opt,name=receiver_key,json=receiverKey,proto3" json:"receiver_key,omitempty"`
	SwapHash             []byte   `protobuf:"bytes,2,opt,name=swap_hash,json=swapHash,proto3" json:"swap_hash,omitempty"`
	Amt                  uint64   `protobuf:"varint,3,opt,name=amt,proto3" json:"amt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerUnchargeSwapRequest) Reset()         { *m = ServerUnchargeSwapRequest{} }
func (m *ServerUnchargeSwapRequest) String() string { return proto.CompactTextString(m) }
func (*ServerUnchargeSwapRequest) ProtoMessage()    {}
func (*ServerUnchargeSwapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_9aa9f93bbf0053c2, []int{0}
}
func (m *ServerUnchargeSwapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerUnchargeSwapRequest.Unmarshal(m, b)
}
func (m *ServerUnchargeSwapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerUnchargeSwapRequest.Marshal(b, m, deterministic)
}
func (dst *ServerUnchargeSwapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerUnchargeSwapRequest.Merge(dst, src)
}
func (m *ServerUnchargeSwapRequest) XXX_Size() int {
	return xxx_messageInfo_ServerUnchargeSwapRequest.Size(m)
}
func (m *ServerUnchargeSwapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerUnchargeSwapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerUnchargeSwapRequest proto.InternalMessageInfo

func (m *ServerUnchargeSwapRequest) GetReceiverKey() []byte {
	if m != nil {
		return m.ReceiverKey
	}
	return nil
}

func (m *ServerUnchargeSwapRequest) GetSwapHash() []byte {
	if m != nil {
		return m.SwapHash
	}
	return nil
}

func (m *ServerUnchargeSwapRequest) GetAmt() uint64 {
	if m != nil {
		return m.Amt
	}
	return 0
}

type ServerUnchargeSwapResponse struct {
	SwapInvoice          string   `protobuf:"bytes,1,opt,name=swap_invoice,json=swapInvoice,proto3" json:"swap_invoice,omitempty"`
	PrepayInvoice        string   `protobuf:"bytes,2,opt,name=prepay_invoice,json=prepayInvoice,proto3" json:"prepay_invoice,omitempty"`
	SenderKey            []byte   `protobuf:"bytes,3,opt,name=sender_key,json=senderKey,proto3" json:"sender_key,omitempty"`
	Expiry               int32    `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerUnchargeSwapResponse) Reset()         { *m = ServerUnchargeSwapResponse{} }
func (m *ServerUnchargeSwapResponse) String() string { return proto.CompactTextString(m) }
func (*ServerUnchargeSwapResponse) ProtoMessage()    {}
func (*ServerUnchargeSwapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_9aa9f93bbf0053c2, []int{1}
}
func (m *ServerUnchargeSwapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerUnchargeSwapResponse.Unmarshal(m, b)
}
func (m *ServerUnchargeSwapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerUnchargeSwapResponse.Marshal(b, m, deterministic)
}
func (dst *ServerUnchargeSwapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerUnchargeSwapResponse.Merge(dst, src)
}
func (m *ServerUnchargeSwapResponse) XXX_Size() int {
	return xxx_messageInfo_ServerUnchargeSwapResponse.Size(m)
}
func (m *ServerUnchargeSwapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerUnchargeSwapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerUnchargeSwapResponse proto.InternalMessageInfo

func (m *ServerUnchargeSwapResponse) GetSwapInvoice() string {
	if m != nil {
		return m.SwapInvoice
	}
	return ""
}

func (m *ServerUnchargeSwapResponse) GetPrepayInvoice() string {
	if m != nil {
		return m.PrepayInvoice
	}
	return ""
}

func (m *ServerUnchargeSwapResponse) GetSenderKey() []byte {
	if m != nil {
		return m.SenderKey
	}
	return nil
}

func (m *ServerUnchargeSwapResponse) GetExpiry() int32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type ServerUnchargeQuoteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerUnchargeQuoteRequest) Reset()         { *m = ServerUnchargeQuoteRequest{} }
func (m *ServerUnchargeQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*ServerUnchargeQuoteRequest) ProtoMessage()    {}
func (*ServerUnchargeQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_9aa9f93bbf0053c2, []int{2}
}
func (m *ServerUnchargeQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerUnchargeQuoteRequest.Unmarshal(m, b)
}
func (m *ServerUnchargeQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerUnchargeQuoteRequest.Marshal(b, m, deterministic)
}
func (dst *ServerUnchargeQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerUnchargeQuoteRequest.Merge(dst, src)
}
func (m *ServerUnchargeQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_ServerUnchargeQuoteRequest.Size(m)
}
func (m *ServerUnchargeQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerUnchargeQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerUnchargeQuoteRequest proto.InternalMessageInfo

type ServerUnchargeQuoteResponse struct {
	SwapPaymentDest      string   `protobuf:"bytes,1,opt,name=swap_payment_dest,json=swapPaymentDest,proto3" json:"swap_payment_dest,omitempty"`
	SwapFeeBase          int64    `protobuf:"varint,2,opt,name=swap_fee_base,json=swapFeeBase,proto3" json:"swap_fee_base,omitempty"`
	SwapFeeRate          int64    `protobuf:"varint,3,opt,name=swap_fee_rate,json=swapFeeRate,proto3" json:"swap_fee_rate,omitempty"`
	PrepayAmt            uint64   `protobuf:"varint,4,opt,name=prepay_amt,json=prepayAmt,proto3" json:"prepay_amt,omitempty"`
	MinSwapAmount        uint64   `protobuf:"varint,5,opt,name=min_swap_amount,json=minSwapAmount,proto3" json:"min_swap_amount,omitempty"`
	MaxSwapAmount        uint64   `protobuf:"varint,6,opt,name=max_swap_amount,json=maxSwapAmount,proto3" json:"max_swap_amount,omitempty"`
	CltvDelta            int32    `protobuf:"varint,7,opt,name=cltv_delta,json=cltvDelta,proto3" json:"cltv_delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerUnchargeQuoteResponse) Reset()         { *m = ServerUnchargeQuoteResponse{} }
func (m *ServerUnchargeQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*ServerUnchargeQuoteResponse) ProtoMessage()    {}
func (*ServerUnchargeQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_9aa9f93bbf0053c2, []int{3}
}
func (m *ServerUnchargeQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerUnchargeQuoteResponse.Unmarshal(m, b)
}
func (m *ServerUnchargeQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerUnchargeQuoteResponse.Marshal(b, m, deterministic)
}
func (dst *ServerUnchargeQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerUnchargeQuoteResponse.Merge(dst, src)
}
func (m *ServerUnchargeQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_ServerUnchargeQuoteResponse.Size(m)
}
func (m *ServerUnchargeQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerUnchargeQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerUnchargeQuoteResponse proto.InternalMessageInfo

func (m *ServerUnchargeQuoteResponse) GetSwapPaymentDest() string {
	if m != nil {
		return m.SwapPaymentDest
	}
	return ""
}

func (m *ServerUnchargeQuoteResponse) GetSwapFeeBase() int64 {
	if m != nil {
		return m.SwapFeeBase
	}
	return 0
}

func (m *ServerUnchargeQuoteResponse) GetSwapFeeRate() int64 {
	if m != nil {
		return m.SwapFeeRate
	}
	return 0
}

func (m *ServerUnchargeQuoteResponse) GetPrepayAmt() uint64 {
	if m != nil {
		return m.PrepayAmt
	}
	return 0
}

func (m *ServerUnchargeQuoteResponse) GetMinSwapAmount() uint64 {
	if m != nil {
		return m.MinSwapAmount
	}
	return 0
}

func (m *ServerUnchargeQuoteResponse) GetMaxSwapAmount() uint64 {
	if m != nil {
		return m.MaxSwapAmount
	}
	return 0
}

func (m *ServerUnchargeQuoteResponse) GetCltvDelta() int32 {
	if m != nil {
		return m.CltvDelta
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerUnchargeSwapRequest)(nil), "looprpc.ServerUnchargeSwapRequest")
	proto.RegisterType((*ServerUnchargeSwapResponse)(nil), "looprpc.ServerUnchargeSwapResponse")
	proto.RegisterType((*ServerUnchargeQuoteRequest)(nil), "looprpc.ServerUnchargeQuoteRequest")
	proto.RegisterType((*ServerUnchargeQuoteResponse)(nil), "looprpc.ServerUnchargeQuoteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SwapServerClient is the client API for SwapServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SwapServerClient interface {
	NewUnchargeSwap(ctx context.Context, in *ServerUnchargeSwapRequest, opts ...grpc.CallOption) (*ServerUnchargeSwapResponse, error)
	UnchargeQuote(ctx context.Context, in *ServerUnchargeQuoteRequest, opts ...grpc.CallOption) (*ServerUnchargeQuoteResponse, error)
}

type swapServerClient struct {
	cc *grpc.ClientConn
}

func NewSwapServerClient(cc *grpc.ClientConn) SwapServerClient {
	return &swapServerClient{cc}
}

func (c *swapServerClient) NewUnchargeSwap(ctx context.Context, in *ServerUnchargeSwapRequest, opts ...grpc.CallOption) (*ServerUnchargeSwapResponse, error) {
	out := new(ServerUnchargeSwapResponse)
	err := c.cc.Invoke(ctx, "/looprpc.SwapServer/NewUnchargeSwap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swapServerClient) UnchargeQuote(ctx context.Context, in *ServerUnchargeQuoteRequest, opts ...grpc.CallOption) (*ServerUnchargeQuoteResponse, error) {
	out := new(ServerUnchargeQuoteResponse)
	err := c.cc.Invoke(ctx, "/looprpc.SwapServer/UnchargeQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwapServerServer is the server API for SwapServer service.
type SwapServerServer interface {
	NewUnchargeSwap(context.Context, *ServerUnchargeSwapRequest) (*ServerUnchargeSwapResponse, error)
	UnchargeQuote(context.Context, *ServerUnchargeQuoteRequest) (*ServerUnchargeQuoteResponse, error)
}

func RegisterSwapServerServer(s *grpc.Server, srv SwapServerServer) {
	s.RegisterService(&_SwapServer_serviceDesc, srv)
}

func _SwapServer_NewUnchargeSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerUnchargeSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServerServer).NewUnchargeSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.SwapServer/NewUnchargeSwap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServerServer).NewUnchargeSwap(ctx, req.(*ServerUnchargeSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwapServer_UnchargeQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerUnchargeQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapServerServer).UnchargeQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/looprpc.SwapServer/UnchargeQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapServerServer).UnchargeQuote(ctx, req.(*ServerUnchargeQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SwapServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "looprpc.SwapServer",
	HandlerType: (*SwapServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUnchargeSwap",
			Handler:    _SwapServer_NewUnchargeSwap_Handler,
		},
		{
			MethodName: "UnchargeQuote",
			Handler:    _SwapServer_UnchargeQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_9aa9f93bbf0053c2) }

var fileDescriptor_server_9aa9f93bbf0053c2 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xdd, 0x6e, 0xd3, 0x40,
	0x10, 0x85, 0xe5, 0x26, 0x4d, 0xc9, 0x34, 0x21, 0xe0, 0x0b, 0x64, 0xd2, 0x56, 0x0a, 0x86, 0x42,
	0xc4, 0x45, 0x22, 0xc1, 0x13, 0xb4, 0xaa, 0x10, 0x08, 0x09, 0x81, 0x2b, 0x6e, 0x72, 0x63, 0x4d,
	0x9c, 0xc1, 0x5e, 0x61, 0xef, 0x2e, 0xbb, 0x9b, 0xbf, 0x87, 0x41, 0xbc, 0x0c, 0x0f, 0x86, 0xf6,
	0xa7, 0x90, 0xa0, 0xb6, 0x77, 0xc9, 0xd9, 0x6f, 0x67, 0xce, 0x9c, 0x59, 0x43, 0x4f, 0x93, 0x5a,
	0x91, 0x9a, 0x48, 0x25, 0x8c, 0x88, 0x8f, 0x6a, 0x21, 0xa4, 0x92, 0xc5, 0xf0, 0xb4, 0x14, 0xa2,
	0xac, 0x69, 0x8a, 0x92, 0x4d, 0x91, 0x73, 0x61, 0xd0, 0x30, 0xc1, 0xb5, 0xc7, 0xd2, 0x06, 0x9e,
	0x5e, 0xbb, 0x6b, 0x5f, 0x79, 0x51, 0xa1, 0x2a, 0xe9, 0x7a, 0x8d, 0x32, 0xa3, 0x1f, 0x4b, 0xd2,
	0x26, 0x7e, 0x06, 0x3d, 0x45, 0x05, 0xb1, 0x15, 0xa9, 0xfc, 0x3b, 0x6d, 0x93, 0x68, 0x14, 0x8d,
	0x7b, 0xd9, 0xf1, 0x8d, 0xf6, 0x91, 0xb6, 0xf1, 0x09, 0x74, 0xf5, 0x1a, 0x65, 0x5e, 0xa1, 0xae,
	0x92, 0x03, 0x77, 0xfe, 0xc0, 0x0a, 0xef, 0x51, 0x57, 0xf1, 0x23, 0x68, 0x61, 0x63, 0x92, 0xd6,
	0x28, 0x1a, 0xb7, 0x33, 0xfb, 0x33, 0xfd, 0x19, 0xc1, 0xf0, 0xb6, 0x7e, 0x5a, 0x0a, 0xae, 0xc9,
	0x36, 0x74, 0xd5, 0x18, 0x5f, 0x09, 0x56, 0x90, 0x6b, 0xd8, 0xcd, 0x8e, 0xad, 0xf6, 0xc1, 0x4b,
	0xf1, 0x39, 0x3c, 0x94, 0x8a, 0x24, 0x6e, 0xff, 0x42, 0x07, 0x0e, 0xea, 0x7b, 0xf5, 0x06, 0x3b,
	0x03, 0xd0, 0xc4, 0x17, 0xc1, 0x78, 0xcb, 0x19, 0xeb, 0x7a, 0xc5, 0xda, 0x7e, 0x02, 0x1d, 0xda,
	0x48, 0xa6, 0xb6, 0x49, 0x7b, 0x14, 0x8d, 0x0f, 0xb3, 0xf0, 0x2f, 0x3d, 0xfd, 0xdf, 0xde, 0x97,
	0xa5, 0x30, 0x14, 0xf2, 0x48, 0x7f, 0x1d, 0xc0, 0xc9, 0xad, 0xc7, 0xc1, 0xfe, 0x6b, 0x78, 0xec,
	0xec, 0x4b, 0xdc, 0x36, 0xc4, 0x4d, 0xbe, 0x20, 0x6d, 0xc2, 0x0c, 0x03, 0x7b, 0xf0, 0xd9, 0xeb,
	0x57, 0x36, 0xdb, 0x14, 0xfa, 0x8e, 0xfd, 0x46, 0x94, 0xcf, 0x51, 0xfb, 0x31, 0x5a, 0x7e, 0xd6,
	0x77, 0x44, 0x97, 0xa8, 0x69, 0x8f, 0x51, 0x68, 0xc8, 0xcd, 0xf1, 0x8f, 0xc9, 0xd0, 0xb8, 0x41,
	0x43, 0x1e, 0x36, 0xea, 0xb6, 0x8b, 0xba, 0xeb, 0x95, 0x8b, 0xc6, 0xc4, 0x2f, 0x61, 0xd0, 0x30,
	0x9e, 0xbb, 0x32, 0xd8, 0x88, 0x25, 0x37, 0xc9, 0xa1, 0x63, 0xfa, 0x0d, 0xe3, 0x36, 0xfb, 0x0b,
	0x27, 0x3a, 0x0e, 0x37, 0x7b, 0x5c, 0x27, 0x70, 0xb8, 0xd9, 0xe1, 0xce, 0x00, 0x8a, 0xda, 0xac,
	0xf2, 0x05, 0xd5, 0x06, 0x93, 0x23, 0x17, 0x5e, 0xd7, 0x2a, 0x57, 0x56, 0x78, 0xf3, 0x3b, 0x02,
	0xb0, 0xb4, 0x4f, 0x29, 0x9e, 0xc1, 0xe0, 0x13, 0xad, 0x77, 0x57, 0x1d, 0xa7, 0x93, 0xf0, 0x30,
	0x27, 0x77, 0xbe, 0xbb, 0xe1, 0xf3, 0x7b, 0x99, 0x10, 0xf6, 0x0c, 0xfa, 0x7b, 0x5b, 0x88, 0xef,
	0xba, 0xb5, 0xbb, 0xc2, 0xe1, 0x8b, 0xfb, 0x21, 0x5f, 0xfb, 0xf2, 0xd5, 0xec, 0xbc, 0x64, 0xa6,
	0x5a, 0xce, 0x27, 0x85, 0x68, 0xa6, 0x35, 0x2b, 0x2b, 0xc3, 0x19, 0x2f, 0x6b, 0x9c, 0xeb, 0xa9,
	0xbd, 0x3f, 0x0d, 0x45, 0xe6, 0x1d, 0xf7, 0x15, 0xbd, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x55,
	0xfc, 0x38, 0x76, 0x7c, 0x03, 0x00, 0x00,
}
