// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AllDeposits(ctx context.Context) ([]Deposit, error)
	AllStaticAddresses(ctx context.Context) ([]StaticAddress, error)
	CancelBatch(ctx context.Context, id int32) error
	CreateDeposit(ctx context.Context, arg CreateDepositParams) error
	CreateReservation(ctx context.Context, arg CreateReservationParams) error
	CreateStaticAddress(ctx context.Context, arg CreateStaticAddressParams) error
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) error
	CreateWithdrawalDeposit(ctx context.Context, arg CreateWithdrawalDepositParams) error
	FetchLiquidityParams(ctx context.Context) ([]byte, error)
	GetAllWithdrawals(ctx context.Context) ([]Withdrawal, error)
	GetBatchSweeps(ctx context.Context, batchID int32) ([]Sweep, error)
	GetBatchSweptAmount(ctx context.Context, batchID int32) (int64, error)
	GetDeposit(ctx context.Context, depositID []byte) (Deposit, error)
	GetInstantOutSwap(ctx context.Context, swapHash []byte) (GetInstantOutSwapRow, error)
	GetInstantOutSwapUpdates(ctx context.Context, swapHash []byte) ([]InstantoutUpdate, error)
	GetInstantOutSwaps(ctx context.Context) ([]GetInstantOutSwapsRow, error)
	GetLastUpdateID(ctx context.Context, swapHash []byte) (int32, error)
	GetLatestDepositUpdate(ctx context.Context, depositID []byte) (DepositUpdate, error)
	GetLoopInSwap(ctx context.Context, swapHash []byte) (GetLoopInSwapRow, error)
	GetLoopInSwapUpdates(ctx context.Context, swapHash []byte) ([]StaticAddressSwapUpdate, error)
	GetLoopInSwaps(ctx context.Context) ([]GetLoopInSwapsRow, error)
	GetLoopOutSwap(ctx context.Context, swapHash []byte) (GetLoopOutSwapRow, error)
	GetLoopOutSwaps(ctx context.Context) ([]GetLoopOutSwapsRow, error)
	GetMigration(ctx context.Context, migrationID string) (MigrationTracker, error)
	GetParentBatch(ctx context.Context, outpoint string) (SweepBatch, error)
	GetReservation(ctx context.Context, reservationID []byte) (Reservation, error)
	GetReservationUpdates(ctx context.Context, reservationID []byte) ([]ReservationUpdate, error)
	GetReservations(ctx context.Context) ([]Reservation, error)
	GetStaticAddress(ctx context.Context, pkscript []byte) (StaticAddress, error)
	GetStaticAddressLoopInSwap(ctx context.Context, swapHash []byte) (GetStaticAddressLoopInSwapRow, error)
	GetStaticAddressLoopInSwapsByStates(ctx context.Context, dollar_1 sql.NullString) ([]GetStaticAddressLoopInSwapsByStatesRow, error)
	GetSwapUpdates(ctx context.Context, swapHash []byte) ([]SwapUpdate, error)
	GetSweepStatus(ctx context.Context, outpoint string) (bool, error)
	GetUnconfirmedBatches(ctx context.Context) ([]SweepBatch, error)
	GetWithdrawalDeposits(ctx context.Context, withdrawalID []byte) ([][]byte, error)
	GetWithdrawalIDByDepositID(ctx context.Context, depositID []byte) ([]byte, error)
	InsertBatch(ctx context.Context, arg InsertBatchParams) (int32, error)
	InsertDepositUpdate(ctx context.Context, arg InsertDepositUpdateParams) error
	InsertHtlcKeys(ctx context.Context, arg InsertHtlcKeysParams) error
	InsertInstantOut(ctx context.Context, arg InsertInstantOutParams) error
	InsertInstantOutUpdate(ctx context.Context, arg InsertInstantOutUpdateParams) error
	InsertLoopIn(ctx context.Context, arg InsertLoopInParams) error
	InsertLoopOut(ctx context.Context, arg InsertLoopOutParams) error
	InsertLoopOutAsset(ctx context.Context, arg InsertLoopOutAssetParams) error
	InsertMigration(ctx context.Context, arg InsertMigrationParams) error
	InsertReservationUpdate(ctx context.Context, arg InsertReservationUpdateParams) error
	InsertStaticAddressLoopIn(ctx context.Context, arg InsertStaticAddressLoopInParams) error
	InsertStaticAddressMetaUpdate(ctx context.Context, arg InsertStaticAddressMetaUpdateParams) error
	InsertSwap(ctx context.Context, arg InsertSwapParams) error
	InsertSwapUpdate(ctx context.Context, arg InsertSwapUpdateParams) error
	IsStored(ctx context.Context, swapHash []byte) (bool, error)
	OverrideSwapCosts(ctx context.Context, arg OverrideSwapCostsParams) error
	UpdateBatch(ctx context.Context, arg UpdateBatchParams) error
	UpdateDeposit(ctx context.Context, arg UpdateDepositParams) error
	UpdateInstantOut(ctx context.Context, arg UpdateInstantOutParams) error
	UpdateLoopOutAssetOffchainPayments(ctx context.Context, arg UpdateLoopOutAssetOffchainPaymentsParams) error
	UpdateReservation(ctx context.Context, arg UpdateReservationParams) error
	UpdateStaticAddressLoopIn(ctx context.Context, arg UpdateStaticAddressLoopInParams) error
	UpdateWithdrawal(ctx context.Context, arg UpdateWithdrawalParams) error
	UpsertLiquidityParams(ctx context.Context, params []byte) error
	UpsertSweep(ctx context.Context, arg UpsertSweepParams) error
}

var _ Querier = (*Queries)(nil)
