// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: static_address_withdrawals.sql

package sqlc

import (
	"context"
)

const allWithdrawals = `-- name: AllWithdrawals :many
SELECT
    id, withdrawal_tx_id, deposit_outpoints, total_deposit_amount, withdrawn_amount, change_amount, confirmation_height
FROM
    withdrawals
ORDER BY
    id ASC
`

func (q *Queries) AllWithdrawals(ctx context.Context) ([]Withdrawal, error) {
	rows, err := q.db.QueryContext(ctx, allWithdrawals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Withdrawal
	for rows.Next() {
		var i Withdrawal
		if err := rows.Scan(
			&i.ID,
			&i.WithdrawalTxID,
			&i.DepositOutpoints,
			&i.TotalDepositAmount,
			&i.WithdrawnAmount,
			&i.ChangeAmount,
			&i.ConfirmationHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWithdrawal = `-- name: CreateWithdrawal :exec
INSERT INTO withdrawals (
    withdrawal_tx_id,
    deposit_outpoints,
    total_deposit_amount,
    withdrawn_amount,
    change_amount,
    confirmation_height
) VALUES (
             $1,
             $2,
             $3,
             $4,
             $5,
             $6
         )
`

type CreateWithdrawalParams struct {
	WithdrawalTxID     string
	DepositOutpoints   string
	TotalDepositAmount int64
	WithdrawnAmount    int64
	ChangeAmount       int64
	ConfirmationHeight int64
}

func (q *Queries) CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) error {
	_, err := q.db.ExecContext(ctx, createWithdrawal,
		arg.WithdrawalTxID,
		arg.DepositOutpoints,
		arg.TotalDepositAmount,
		arg.WithdrawnAmount,
		arg.ChangeAmount,
		arg.ConfirmationHeight,
	)
	return err
}
