// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: staticaddr.proto

// We can't change this to swapserverrpc, it would be a breaking change because
// the package name is also contained in the HTTP URIs and old clients would
// call the wrong endpoints. Luckily with the go_package option we can have
// different golang and RPC package names to fix protobuf namespace conflicts.

package swapserverrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StaticAddressProtocolVersion represents the static address protocol version
// the client adheres to.
type StaticAddressProtocolVersion int32

const (
	// V0 is the initially released static address protocol version.
	StaticAddressProtocolVersion_V0 StaticAddressProtocolVersion = 0
)

// Enum value maps for StaticAddressProtocolVersion.
var (
	StaticAddressProtocolVersion_name = map[int32]string{
		0: "V0",
	}
	StaticAddressProtocolVersion_value = map[string]int32{
		"V0": 0,
	}
)

func (x StaticAddressProtocolVersion) Enum() *StaticAddressProtocolVersion {
	p := new(StaticAddressProtocolVersion)
	*p = x
	return p
}

func (x StaticAddressProtocolVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StaticAddressProtocolVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_staticaddr_proto_enumTypes[0].Descriptor()
}

func (StaticAddressProtocolVersion) Type() protoreflect.EnumType {
	return &file_staticaddr_proto_enumTypes[0]
}

func (x StaticAddressProtocolVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StaticAddressProtocolVersion.Descriptor instead.
func (StaticAddressProtocolVersion) EnumDescriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{0}
}

type ServerNewAddressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol version that the client adheres to.
	ProtocolVersion StaticAddressProtocolVersion `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3,enum=looprpc.StaticAddressProtocolVersion" json:"protocol_version,omitempty"`
	// The client key for the MuSig2 static address output.
	ClientKey     []byte `protobuf:"bytes,2,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerNewAddressRequest) Reset() {
	*x = ServerNewAddressRequest{}
	mi := &file_staticaddr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerNewAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerNewAddressRequest) ProtoMessage() {}

func (x *ServerNewAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerNewAddressRequest.ProtoReflect.Descriptor instead.
func (*ServerNewAddressRequest) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{0}
}

func (x *ServerNewAddressRequest) GetProtocolVersion() StaticAddressProtocolVersion {
	if x != nil {
		return x.ProtocolVersion
	}
	return StaticAddressProtocolVersion_V0
}

func (x *ServerNewAddressRequest) GetClientKey() []byte {
	if x != nil {
		return x.ClientKey
	}
	return nil
}

type ServerNewAddressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server address parameters that the client needs to know to create the
	// static address output.
	Params        *ServerAddressParameters `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerNewAddressResponse) Reset() {
	*x = ServerNewAddressResponse{}
	mi := &file_staticaddr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerNewAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerNewAddressResponse) ProtoMessage() {}

func (x *ServerNewAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerNewAddressResponse.ProtoReflect.Descriptor instead.
func (*ServerNewAddressResponse) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{1}
}

func (x *ServerNewAddressResponse) GetParams() *ServerAddressParameters {
	if x != nil {
		return x.Params
	}
	return nil
}

type ServerAddressParameters struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server key for the MuSig2 static address output.
	ServerKey []byte `protobuf:"bytes,1,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	// The CSV expiry of the static address output.
	Expiry        uint32 `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerAddressParameters) Reset() {
	*x = ServerAddressParameters{}
	mi := &file_staticaddr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAddressParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAddressParameters) ProtoMessage() {}

func (x *ServerAddressParameters) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAddressParameters.ProtoReflect.Descriptor instead.
func (*ServerAddressParameters) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{2}
}

func (x *ServerAddressParameters) GetServerKey() []byte {
	if x != nil {
		return x.ServerKey
	}
	return nil
}

func (x *ServerAddressParameters) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

// Deprecated: use ServerPsbtWithdrawRequest instead.
//
// Deprecated: Marked as deprecated in staticaddr.proto.
type ServerWithdrawRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The deposit outpoints the client wishes to withdraw.
	Outpoints []*PrevoutInfo `protobuf:"bytes,1,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	// The nonces that the client used to generate the withdrawal tx sigs.
	ClientNonces [][]byte `protobuf:"bytes,2,rep,name=client_nonces,json=clientNonces,proto3" json:"client_nonces,omitempty"`
	// The address that the client wants to sweep the static address deposits
	// to.
	ClientSweepAddr string `protobuf:"bytes,3,opt,name=client_sweep_addr,json=clientSweepAddr,proto3" json:"client_sweep_addr,omitempty"`
	// The fee rate in sat/kw that the client wants to use for the sweep.
	TxFeeRate uint64 `protobuf:"varint,4,opt,name=tx_fee_rate,json=txFeeRate,proto3" json:"tx_fee_rate,omitempty"`
	// The amount that the client wants to withdraw, in satoshis. This amount
	// can be a fraction of the total deposit amount.
	WithdrawAmount int64 `protobuf:"varint,5,opt,name=withdraw_amount,json=withdrawAmount,proto3" json:"withdraw_amount,omitempty"`
	// The change amount will be sent back to the static address. The client
	// ensures that the change amount covers the transaction fee, and that the
	// change after fees is at least the dust limit.
	ChangeAmount  int64 `protobuf:"varint,6,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerWithdrawRequest) Reset() {
	*x = ServerWithdrawRequest{}
	mi := &file_staticaddr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerWithdrawRequest) ProtoMessage() {}

func (x *ServerWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerWithdrawRequest.ProtoReflect.Descriptor instead.
func (*ServerWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{3}
}

func (x *ServerWithdrawRequest) GetOutpoints() []*PrevoutInfo {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

func (x *ServerWithdrawRequest) GetClientNonces() [][]byte {
	if x != nil {
		return x.ClientNonces
	}
	return nil
}

func (x *ServerWithdrawRequest) GetClientSweepAddr() string {
	if x != nil {
		return x.ClientSweepAddr
	}
	return ""
}

func (x *ServerWithdrawRequest) GetTxFeeRate() uint64 {
	if x != nil {
		return x.TxFeeRate
	}
	return 0
}

func (x *ServerWithdrawRequest) GetWithdrawAmount() int64 {
	if x != nil {
		return x.WithdrawAmount
	}
	return 0
}

func (x *ServerWithdrawRequest) GetChangeAmount() int64 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

// Deprecated: use ServerPsbtWithdrawResponse instead.
//
// Deprecated: Marked as deprecated in staticaddr.proto.
type ServerWithdrawResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sweep sigs that the server generated for the withdrawal tx.
	Musig2SweepSigs [][]byte `protobuf:"bytes,1,rep,name=musig2_sweep_sigs,json=musig2SweepSigs,proto3" json:"musig2_sweep_sigs,omitempty"`
	// The nonces that the server used to generate the withdrawal sigs.
	ServerNonces  [][]byte `protobuf:"bytes,2,rep,name=server_nonces,json=serverNonces,proto3" json:"server_nonces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerWithdrawResponse) Reset() {
	*x = ServerWithdrawResponse{}
	mi := &file_staticaddr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerWithdrawResponse) ProtoMessage() {}

func (x *ServerWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerWithdrawResponse.ProtoReflect.Descriptor instead.
func (*ServerWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{4}
}

func (x *ServerWithdrawResponse) GetMusig2SweepSigs() [][]byte {
	if x != nil {
		return x.Musig2SweepSigs
	}
	return nil
}

func (x *ServerWithdrawResponse) GetServerNonces() [][]byte {
	if x != nil {
		return x.ServerNonces
	}
	return nil
}

type ServerPsbtWithdrawRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The withdrawal psbt.
	// Note that txscript.SigHashDefault will be enforced by default.
	WithdrawalPsbt []byte `protobuf:"bytes,1,opt,name=withdrawal_psbt,json=withdrawalPsbt,proto3" json:"withdrawal_psbt,omitempty"`
	// The map of deposit txid:idx to the nonce used by the client.
	DepositToNonces map[string][]byte `protobuf:"bytes,2,rep,name=deposit_to_nonces,json=depositToNonces,proto3" json:"deposit_to_nonces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerPsbtWithdrawRequest) Reset() {
	*x = ServerPsbtWithdrawRequest{}
	mi := &file_staticaddr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPsbtWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPsbtWithdrawRequest) ProtoMessage() {}

func (x *ServerPsbtWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPsbtWithdrawRequest.ProtoReflect.Descriptor instead.
func (*ServerPsbtWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{5}
}

func (x *ServerPsbtWithdrawRequest) GetWithdrawalPsbt() []byte {
	if x != nil {
		return x.WithdrawalPsbt
	}
	return nil
}

func (x *ServerPsbtWithdrawRequest) GetDepositToNonces() map[string][]byte {
	if x != nil {
		return x.DepositToNonces
	}
	return nil
}

type ServerPsbtWithdrawResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The txid of the psbt that the client wants to push the sigs for.
	Txid []byte `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	// A map of deposits in format txid:idx to the nonces.
	SigningInfo   map[string]*ServerPsbtWithdrawSigningInfo `protobuf:"bytes,2,rep,name=signing_info,json=signingInfo,proto3" json:"signing_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPsbtWithdrawResponse) Reset() {
	*x = ServerPsbtWithdrawResponse{}
	mi := &file_staticaddr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPsbtWithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPsbtWithdrawResponse) ProtoMessage() {}

func (x *ServerPsbtWithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPsbtWithdrawResponse.ProtoReflect.Descriptor instead.
func (*ServerPsbtWithdrawResponse) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{6}
}

func (x *ServerPsbtWithdrawResponse) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *ServerPsbtWithdrawResponse) GetSigningInfo() map[string]*ServerPsbtWithdrawSigningInfo {
	if x != nil {
		return x.SigningInfo
	}
	return nil
}

type ServerPsbtWithdrawSigningInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The nonces that the client used to generate the partial withdrawal tx
	// sigs.
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The musig2 htlc sigs that the client generated for the withdrawal tx.
	Sig           []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPsbtWithdrawSigningInfo) Reset() {
	*x = ServerPsbtWithdrawSigningInfo{}
	mi := &file_staticaddr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPsbtWithdrawSigningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPsbtWithdrawSigningInfo) ProtoMessage() {}

func (x *ServerPsbtWithdrawSigningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPsbtWithdrawSigningInfo.ProtoReflect.Descriptor instead.
func (*ServerPsbtWithdrawSigningInfo) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{7}
}

func (x *ServerPsbtWithdrawSigningInfo) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ServerPsbtWithdrawSigningInfo) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type ServerStaticAddressLoopInRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client's public key for the htlc output.
	HtlcClientPubKey []byte `protobuf:"bytes,1,opt,name=htlc_client_pub_key,json=htlcClientPubKey,proto3" json:"htlc_client_pub_key,omitempty"`
	// The hashed swap invoice preimage of the swap.
	SwapHash []byte `protobuf:"bytes,2,opt,name=swap_hash,json=swapHash,proto3" json:"swap_hash,omitempty"`
	// The deposit outpoints the client wishes to loop in. They implicitly state
	// the swap amount if the amount field is not specified. If the amount field
	// is specified, the server will use the total amount of the deposit
	// outpoints minus the amount as the change amount.
	DepositOutpoints []string `protobuf:"bytes,3,rep,name=deposit_outpoints,json=depositOutpoints,proto3" json:"deposit_outpoints,omitempty"`
	// The swap invoice that the client wants the server to pay.
	SwapInvoice string `protobuf:"bytes,4,opt,name=swap_invoice,json=swapInvoice,proto3" json:"swap_invoice,omitempty"`
	// An optional last hop the client wants to receive the invoice payment
	// from.
	LastHop []byte `protobuf:"bytes,5,opt,name=last_hop,json=lastHop,proto3" json:"last_hop,omitempty"`
	// The protocol version that the client adheres to.
	ProtocolVersion StaticAddressProtocolVersion `protobuf:"varint,6,opt,name=protocol_version,json=protocolVersion,proto3,enum=looprpc.StaticAddressProtocolVersion" json:"protocol_version,omitempty"`
	// The user agent string that identifies the software running on the user's
	// side. This can be changed in the user's client software but it _SHOULD_
	// conform to the following pattern:
	//
	//	Agent-Name/semver-version(/additional-info)
	//
	// Examples:
	//
	//	loopd/v0.10.0-beta/commit=3b635821
	//	litd/v0.2.0-alpha/commit=326d754
	//	loopd/v0.10.0-beta/commit=3b635823,initiator=easy-autoloop
	UserAgent string `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// The swap payment timeout allows the user to specify an upper limit for
	// the amount of time the server is allowed to take to fulfill the off-chain
	// swap payment. If the timeout is reached the swap will be aborted on the
	// server side and the client can retry the swap with different parameters.
	PaymentTimeoutSeconds uint32 `protobuf:"varint,8,opt,name=payment_timeout_seconds,json=paymentTimeoutSeconds,proto3" json:"payment_timeout_seconds,omitempty"`
	// The optional swap amount in satoshis the client is attempting to swap. If
	// specified the server will take out this amount from the total value of
	// provided deposit_outpoints and will send the change back to the static
	// address. If this results in dust change the server will reject the swap
	// request. If the amount is not specified the server will use the total amount
	// of the deposit_outpoints as swap amount without providing an additional
	// flag - this is to maintain backwards compatibility.
	Amount uint64 `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	// If set, request the server to use fast publication behavior for this
	// swap.
	Fast          bool `protobuf:"varint,10,opt,name=fast,proto3" json:"fast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStaticAddressLoopInRequest) Reset() {
	*x = ServerStaticAddressLoopInRequest{}
	mi := &file_staticaddr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStaticAddressLoopInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStaticAddressLoopInRequest) ProtoMessage() {}

func (x *ServerStaticAddressLoopInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStaticAddressLoopInRequest.ProtoReflect.Descriptor instead.
func (*ServerStaticAddressLoopInRequest) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{8}
}

func (x *ServerStaticAddressLoopInRequest) GetHtlcClientPubKey() []byte {
	if x != nil {
		return x.HtlcClientPubKey
	}
	return nil
}

func (x *ServerStaticAddressLoopInRequest) GetSwapHash() []byte {
	if x != nil {
		return x.SwapHash
	}
	return nil
}

func (x *ServerStaticAddressLoopInRequest) GetDepositOutpoints() []string {
	if x != nil {
		return x.DepositOutpoints
	}
	return nil
}

func (x *ServerStaticAddressLoopInRequest) GetSwapInvoice() string {
	if x != nil {
		return x.SwapInvoice
	}
	return ""
}

func (x *ServerStaticAddressLoopInRequest) GetLastHop() []byte {
	if x != nil {
		return x.LastHop
	}
	return nil
}

func (x *ServerStaticAddressLoopInRequest) GetProtocolVersion() StaticAddressProtocolVersion {
	if x != nil {
		return x.ProtocolVersion
	}
	return StaticAddressProtocolVersion_V0
}

func (x *ServerStaticAddressLoopInRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ServerStaticAddressLoopInRequest) GetPaymentTimeoutSeconds() uint32 {
	if x != nil {
		return x.PaymentTimeoutSeconds
	}
	return 0
}

func (x *ServerStaticAddressLoopInRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ServerStaticAddressLoopInRequest) GetFast() bool {
	if x != nil {
		return x.Fast
	}
	return false
}

type ServerStaticAddressLoopInResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The server's public key for the htlc output.
	HtlcServerPubKey []byte `protobuf:"bytes,1,opt,name=htlc_server_pub_key,json=htlcServerPubKey,proto3" json:"htlc_server_pub_key,omitempty"`
	// The cltv expiry height for the htlc. This is the height at which the
	// htlc will expire and the client is free to claim the funds back.
	HtlcExpiry int32 `protobuf:"varint,2,opt,name=htlc_expiry,json=htlcExpiry,proto3" json:"htlc_expiry,omitempty"`
	// The info the server used to generate the standard fee partial htlc tx
	// sigs.
	StandardHtlcInfo *ServerHtlcSigningInfo `protobuf:"bytes,3,opt,name=standard_htlc_info,json=standardHtlcInfo,proto3" json:"standard_htlc_info,omitempty"`
	// The info the server used to generate the high fee partial htlc tx sigs.
	HighFeeHtlcInfo *ServerHtlcSigningInfo `protobuf:"bytes,4,opt,name=high_fee_htlc_info,json=highFeeHtlcInfo,proto3" json:"high_fee_htlc_info,omitempty"`
	// The info the server used to generate the extreme fee partial htlc tx
	// sigs.
	ExtremeFeeHtlcInfo *ServerHtlcSigningInfo `protobuf:"bytes,5,opt,name=extreme_fee_htlc_info,json=extremeFeeHtlcInfo,proto3" json:"extreme_fee_htlc_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerStaticAddressLoopInResponse) Reset() {
	*x = ServerStaticAddressLoopInResponse{}
	mi := &file_staticaddr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStaticAddressLoopInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStaticAddressLoopInResponse) ProtoMessage() {}

func (x *ServerStaticAddressLoopInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStaticAddressLoopInResponse.ProtoReflect.Descriptor instead.
func (*ServerStaticAddressLoopInResponse) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{9}
}

func (x *ServerStaticAddressLoopInResponse) GetHtlcServerPubKey() []byte {
	if x != nil {
		return x.HtlcServerPubKey
	}
	return nil
}

func (x *ServerStaticAddressLoopInResponse) GetHtlcExpiry() int32 {
	if x != nil {
		return x.HtlcExpiry
	}
	return 0
}

func (x *ServerStaticAddressLoopInResponse) GetStandardHtlcInfo() *ServerHtlcSigningInfo {
	if x != nil {
		return x.StandardHtlcInfo
	}
	return nil
}

func (x *ServerStaticAddressLoopInResponse) GetHighFeeHtlcInfo() *ServerHtlcSigningInfo {
	if x != nil {
		return x.HighFeeHtlcInfo
	}
	return nil
}

func (x *ServerStaticAddressLoopInResponse) GetExtremeFeeHtlcInfo() *ServerHtlcSigningInfo {
	if x != nil {
		return x.ExtremeFeeHtlcInfo
	}
	return nil
}

type ServerHtlcSigningInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The nonces that the server used to generate the partial htlc tx sigs.
	Nonces [][]byte `protobuf:"bytes,1,rep,name=nonces,proto3" json:"nonces,omitempty"`
	// The fee rate in sat/kw that the server wants to use for the htlc tx.
	FeeRate       uint64 `protobuf:"varint,2,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHtlcSigningInfo) Reset() {
	*x = ServerHtlcSigningInfo{}
	mi := &file_staticaddr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHtlcSigningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHtlcSigningInfo) ProtoMessage() {}

func (x *ServerHtlcSigningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHtlcSigningInfo.ProtoReflect.Descriptor instead.
func (*ServerHtlcSigningInfo) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{10}
}

func (x *ServerHtlcSigningInfo) GetNonces() [][]byte {
	if x != nil {
		return x.Nonces
	}
	return nil
}

func (x *ServerHtlcSigningInfo) GetFeeRate() uint64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

type PushStaticAddressHtlcSigsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The swap hash that the client wants to push the htlc sigs for.
	SwapHash []byte `protobuf:"bytes,1,opt,name=swap_hash,json=swapHash,proto3" json:"swap_hash,omitempty"`
	// The nonces that the client used to generate the htlc sigs.
	StandardHtlcInfo *ClientHtlcSigningInfo `protobuf:"bytes,2,opt,name=standard_htlc_info,json=standardHtlcInfo,proto3" json:"standard_htlc_info,omitempty"`
	// The nonces that the client used to generate the high fee htlc sigs.
	HighFeeHtlcInfo *ClientHtlcSigningInfo `protobuf:"bytes,3,opt,name=high_fee_htlc_info,json=highFeeHtlcInfo,proto3" json:"high_fee_htlc_info,omitempty"`
	// The nonces that the client used to generate the extreme fee htlc sigs.
	ExtremeFeeHtlcInfo *ClientHtlcSigningInfo `protobuf:"bytes,4,opt,name=extreme_fee_htlc_info,json=extremeFeeHtlcInfo,proto3" json:"extreme_fee_htlc_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PushStaticAddressHtlcSigsRequest) Reset() {
	*x = PushStaticAddressHtlcSigsRequest{}
	mi := &file_staticaddr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStaticAddressHtlcSigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStaticAddressHtlcSigsRequest) ProtoMessage() {}

func (x *PushStaticAddressHtlcSigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStaticAddressHtlcSigsRequest.ProtoReflect.Descriptor instead.
func (*PushStaticAddressHtlcSigsRequest) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{11}
}

func (x *PushStaticAddressHtlcSigsRequest) GetSwapHash() []byte {
	if x != nil {
		return x.SwapHash
	}
	return nil
}

func (x *PushStaticAddressHtlcSigsRequest) GetStandardHtlcInfo() *ClientHtlcSigningInfo {
	if x != nil {
		return x.StandardHtlcInfo
	}
	return nil
}

func (x *PushStaticAddressHtlcSigsRequest) GetHighFeeHtlcInfo() *ClientHtlcSigningInfo {
	if x != nil {
		return x.HighFeeHtlcInfo
	}
	return nil
}

func (x *PushStaticAddressHtlcSigsRequest) GetExtremeFeeHtlcInfo() *ClientHtlcSigningInfo {
	if x != nil {
		return x.ExtremeFeeHtlcInfo
	}
	return nil
}

type ClientHtlcSigningInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The nonces that the client used to generate the partial htlc tx sigs.
	Nonces [][]byte `protobuf:"bytes,1,rep,name=nonces,proto3" json:"nonces,omitempty"`
	// The musig2 htlc sigs that the client generated for the htlc tx.
	Sigs          [][]byte `protobuf:"bytes,2,rep,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHtlcSigningInfo) Reset() {
	*x = ClientHtlcSigningInfo{}
	mi := &file_staticaddr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHtlcSigningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHtlcSigningInfo) ProtoMessage() {}

func (x *ClientHtlcSigningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHtlcSigningInfo.ProtoReflect.Descriptor instead.
func (*ClientHtlcSigningInfo) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{12}
}

func (x *ClientHtlcSigningInfo) GetNonces() [][]byte {
	if x != nil {
		return x.Nonces
	}
	return nil
}

func (x *ClientHtlcSigningInfo) GetSigs() [][]byte {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type PushStaticAddressHtlcSigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStaticAddressHtlcSigsResponse) Reset() {
	*x = PushStaticAddressHtlcSigsResponse{}
	mi := &file_staticaddr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStaticAddressHtlcSigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStaticAddressHtlcSigsResponse) ProtoMessage() {}

func (x *PushStaticAddressHtlcSigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStaticAddressHtlcSigsResponse.ProtoReflect.Descriptor instead.
func (*PushStaticAddressHtlcSigsResponse) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{13}
}

type PushStaticAddressSweeplessSigsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The swap hash of the swap that the client wants to push the sweepless
	// sigs for.
	SwapHash []byte `protobuf:"bytes,1,opt,name=swap_hash,json=swapHash,proto3" json:"swap_hash,omitempty"`
	// The txid of the sweep tx that the client wants to push the sweepless
	// sigs for.
	Txid []byte `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	// A map of deposits in format txid:idx to the nonces.
	SigningInfo map[string]*ClientSweeplessSigningInfo `protobuf:"bytes,3,rep,name=signing_info,json=signingInfo,proto3" json:"signing_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// An optional error message that the client can provide, e.g. if the
	// client does not consider the swap finished yet.bool
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStaticAddressSweeplessSigsRequest) Reset() {
	*x = PushStaticAddressSweeplessSigsRequest{}
	mi := &file_staticaddr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStaticAddressSweeplessSigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStaticAddressSweeplessSigsRequest) ProtoMessage() {}

func (x *PushStaticAddressSweeplessSigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStaticAddressSweeplessSigsRequest.ProtoReflect.Descriptor instead.
func (*PushStaticAddressSweeplessSigsRequest) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{14}
}

func (x *PushStaticAddressSweeplessSigsRequest) GetSwapHash() []byte {
	if x != nil {
		return x.SwapHash
	}
	return nil
}

func (x *PushStaticAddressSweeplessSigsRequest) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *PushStaticAddressSweeplessSigsRequest) GetSigningInfo() map[string]*ClientSweeplessSigningInfo {
	if x != nil {
		return x.SigningInfo
	}
	return nil
}

func (x *PushStaticAddressSweeplessSigsRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ClientSweeplessSigningInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The nonces that the client used to generate the partial sweepless tx
	// sigs.
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The musig2 htlc sigs that the client generated for the sweepless tx.
	Sig           []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSweeplessSigningInfo) Reset() {
	*x = ClientSweeplessSigningInfo{}
	mi := &file_staticaddr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSweeplessSigningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSweeplessSigningInfo) ProtoMessage() {}

func (x *ClientSweeplessSigningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSweeplessSigningInfo.ProtoReflect.Descriptor instead.
func (*ClientSweeplessSigningInfo) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{15}
}

func (x *ClientSweeplessSigningInfo) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *ClientSweeplessSigningInfo) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type PushStaticAddressSweeplessSigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushStaticAddressSweeplessSigsResponse) Reset() {
	*x = PushStaticAddressSweeplessSigsResponse{}
	mi := &file_staticaddr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushStaticAddressSweeplessSigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushStaticAddressSweeplessSigsResponse) ProtoMessage() {}

func (x *PushStaticAddressSweeplessSigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staticaddr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushStaticAddressSweeplessSigsResponse.ProtoReflect.Descriptor instead.
func (*PushStaticAddressSweeplessSigsResponse) Descriptor() ([]byte, []int) {
	return file_staticaddr_proto_rawDescGZIP(), []int{16}
}

var File_staticaddr_proto protoreflect.FileDescriptor

const file_staticaddr_proto_rawDesc = "" +
	"\n" +
	"\x10staticaddr.proto\x12\alooprpc\x1a\fserver.proto\"\x8a\x01\n" +
	"\x17ServerNewAddressRequest\x12P\n" +
	"\x10protocol_version\x18\x01 \x01(\x0e2%.looprpc.StaticAddressProtocolVersionR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"client_key\x18\x02 \x01(\fR\tclientKey\"T\n" +
	"\x18ServerNewAddressResponse\x128\n" +
	"\x06params\x18\x01 \x01(\v2 .looprpc.ServerAddressParametersR\x06params\"P\n" +
	"\x17ServerAddressParameters\x12\x1d\n" +
	"\n" +
	"server_key\x18\x01 \x01(\fR\tserverKey\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\rR\x06expiry\"\x8e\x02\n" +
	"\x15ServerWithdrawRequest\x122\n" +
	"\toutpoints\x18\x01 \x03(\v2\x14.looprpc.PrevoutInfoR\toutpoints\x12#\n" +
	"\rclient_nonces\x18\x02 \x03(\fR\fclientNonces\x12*\n" +
	"\x11client_sweep_addr\x18\x03 \x01(\tR\x0fclientSweepAddr\x12\x1e\n" +
	"\vtx_fee_rate\x18\x04 \x01(\x04R\ttxFeeRate\x12'\n" +
	"\x0fwithdraw_amount\x18\x05 \x01(\x03R\x0ewithdrawAmount\x12#\n" +
	"\rchange_amount\x18\x06 \x01(\x03R\fchangeAmount:\x02\x18\x01\"m\n" +
	"\x16ServerWithdrawResponse\x12*\n" +
	"\x11musig2_sweep_sigs\x18\x01 \x03(\fR\x0fmusig2SweepSigs\x12#\n" +
	"\rserver_nonces\x18\x02 \x03(\fR\fserverNonces:\x02\x18\x01\"\xed\x01\n" +
	"\x19ServerPsbtWithdrawRequest\x12'\n" +
	"\x0fwithdrawal_psbt\x18\x01 \x01(\fR\x0ewithdrawalPsbt\x12c\n" +
	"\x11deposit_to_nonces\x18\x02 \x03(\v27.looprpc.ServerPsbtWithdrawRequest.DepositToNoncesEntryR\x0fdepositToNonces\x1aB\n" +
	"\x14DepositToNoncesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xf1\x01\n" +
	"\x1aServerPsbtWithdrawResponse\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12W\n" +
	"\fsigning_info\x18\x02 \x03(\v24.looprpc.ServerPsbtWithdrawResponse.SigningInfoEntryR\vsigningInfo\x1af\n" +
	"\x10SigningInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.looprpc.ServerPsbtWithdrawSigningInfoR\x05value:\x028\x01\"G\n" +
	"\x1dServerPsbtWithdrawSigningInfo\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"\xae\x03\n" +
	" ServerStaticAddressLoopInRequest\x12-\n" +
	"\x13htlc_client_pub_key\x18\x01 \x01(\fR\x10htlcClientPubKey\x12\x1b\n" +
	"\tswap_hash\x18\x02 \x01(\fR\bswapHash\x12+\n" +
	"\x11deposit_outpoints\x18\x03 \x03(\tR\x10depositOutpoints\x12!\n" +
	"\fswap_invoice\x18\x04 \x01(\tR\vswapInvoice\x12\x19\n" +
	"\blast_hop\x18\x05 \x01(\fR\alastHop\x12P\n" +
	"\x10protocol_version\x18\x06 \x01(\x0e2%.looprpc.StaticAddressProtocolVersionR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\x126\n" +
	"\x17payment_timeout_seconds\x18\b \x01(\rR\x15paymentTimeoutSeconds\x12\x16\n" +
	"\x06amount\x18\t \x01(\x04R\x06amount\x12\x12\n" +
	"\x04fast\x18\n" +
	" \x01(\bR\x04fast\"\xe1\x02\n" +
	"!ServerStaticAddressLoopInResponse\x12-\n" +
	"\x13htlc_server_pub_key\x18\x01 \x01(\fR\x10htlcServerPubKey\x12\x1f\n" +
	"\vhtlc_expiry\x18\x02 \x01(\x05R\n" +
	"htlcExpiry\x12L\n" +
	"\x12standard_htlc_info\x18\x03 \x01(\v2\x1e.looprpc.ServerHtlcSigningInfoR\x10standardHtlcInfo\x12K\n" +
	"\x12high_fee_htlc_info\x18\x04 \x01(\v2\x1e.looprpc.ServerHtlcSigningInfoR\x0fhighFeeHtlcInfo\x12Q\n" +
	"\x15extreme_fee_htlc_info\x18\x05 \x01(\v2\x1e.looprpc.ServerHtlcSigningInfoR\x12extremeFeeHtlcInfo\"J\n" +
	"\x15ServerHtlcSigningInfo\x12\x16\n" +
	"\x06nonces\x18\x01 \x03(\fR\x06nonces\x12\x19\n" +
	"\bfee_rate\x18\x02 \x01(\x04R\afeeRate\"\xad\x02\n" +
	" PushStaticAddressHtlcSigsRequest\x12\x1b\n" +
	"\tswap_hash\x18\x01 \x01(\fR\bswapHash\x12L\n" +
	"\x12standard_htlc_info\x18\x02 \x01(\v2\x1e.looprpc.ClientHtlcSigningInfoR\x10standardHtlcInfo\x12K\n" +
	"\x12high_fee_htlc_info\x18\x03 \x01(\v2\x1e.looprpc.ClientHtlcSigningInfoR\x0fhighFeeHtlcInfo\x12Q\n" +
	"\x15extreme_fee_htlc_info\x18\x04 \x01(\v2\x1e.looprpc.ClientHtlcSigningInfoR\x12extremeFeeHtlcInfo\"C\n" +
	"\x15ClientHtlcSigningInfo\x12\x16\n" +
	"\x06nonces\x18\x01 \x03(\fR\x06nonces\x12\x12\n" +
	"\x04sigs\x18\x02 \x03(\fR\x04sigs\"#\n" +
	"!PushStaticAddressHtlcSigsResponse\"\xc6\x02\n" +
	"%PushStaticAddressSweeplessSigsRequest\x12\x1b\n" +
	"\tswap_hash\x18\x01 \x01(\fR\bswapHash\x12\x12\n" +
	"\x04txid\x18\x02 \x01(\fR\x04txid\x12b\n" +
	"\fsigning_info\x18\x03 \x03(\v2?.looprpc.PushStaticAddressSweeplessSigsRequest.SigningInfoEntryR\vsigningInfo\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x1ac\n" +
	"\x10SigningInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.looprpc.ClientSweeplessSigningInfoR\x05value:\x028\x01\"D\n" +
	"\x1aClientSweeplessSigningInfo\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"(\n" +
	"&PushStaticAddressSweeplessSigsResponse*&\n" +
	"\x1cStaticAddressProtocolVersion\x12\x06\n" +
	"\x02V0\x10\x002\xa1\x05\n" +
	"\x13StaticAddressServer\x12W\n" +
	"\x10ServerNewAddress\x12 .looprpc.ServerNewAddressRequest\x1a!.looprpc.ServerNewAddressResponse\x12^\n" +
	"\x16ServerWithdrawDeposits\x12\x1e.looprpc.ServerWithdrawRequest\x1a\x1f.looprpc.ServerWithdrawResponse\"\x03\x88\x02\x01\x12e\n" +
	"\x1aServerPsbtWithdrawDeposits\x12\".looprpc.ServerPsbtWithdrawRequest\x1a#.looprpc.ServerPsbtWithdrawResponse\x12r\n" +
	"\x19ServerStaticAddressLoopIn\x12).looprpc.ServerStaticAddressLoopInRequest\x1a*.looprpc.ServerStaticAddressLoopInResponse\x12r\n" +
	"\x19PushStaticAddressHtlcSigs\x12).looprpc.PushStaticAddressHtlcSigsRequest\x1a*.looprpc.PushStaticAddressHtlcSigsResponse\x12\x81\x01\n" +
	"\x1ePushStaticAddressSweeplessSigs\x12..looprpc.PushStaticAddressSweeplessSigsRequest\x1a/.looprpc.PushStaticAddressSweeplessSigsResponseB-Z+github.com/lightninglabs/loop/swapserverrpcb\x06proto3"

var (
	file_staticaddr_proto_rawDescOnce sync.Once
	file_staticaddr_proto_rawDescData []byte
)

func file_staticaddr_proto_rawDescGZIP() []byte {
	file_staticaddr_proto_rawDescOnce.Do(func() {
		file_staticaddr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staticaddr_proto_rawDesc), len(file_staticaddr_proto_rawDesc)))
	})
	return file_staticaddr_proto_rawDescData
}

var file_staticaddr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_staticaddr_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_staticaddr_proto_goTypes = []any{
	(StaticAddressProtocolVersion)(0),              // 0: looprpc.StaticAddressProtocolVersion
	(*ServerNewAddressRequest)(nil),                // 1: looprpc.ServerNewAddressRequest
	(*ServerNewAddressResponse)(nil),               // 2: looprpc.ServerNewAddressResponse
	(*ServerAddressParameters)(nil),                // 3: looprpc.ServerAddressParameters
	(*ServerWithdrawRequest)(nil),                  // 4: looprpc.ServerWithdrawRequest
	(*ServerWithdrawResponse)(nil),                 // 5: looprpc.ServerWithdrawResponse
	(*ServerPsbtWithdrawRequest)(nil),              // 6: looprpc.ServerPsbtWithdrawRequest
	(*ServerPsbtWithdrawResponse)(nil),             // 7: looprpc.ServerPsbtWithdrawResponse
	(*ServerPsbtWithdrawSigningInfo)(nil),          // 8: looprpc.ServerPsbtWithdrawSigningInfo
	(*ServerStaticAddressLoopInRequest)(nil),       // 9: looprpc.ServerStaticAddressLoopInRequest
	(*ServerStaticAddressLoopInResponse)(nil),      // 10: looprpc.ServerStaticAddressLoopInResponse
	(*ServerHtlcSigningInfo)(nil),                  // 11: looprpc.ServerHtlcSigningInfo
	(*PushStaticAddressHtlcSigsRequest)(nil),       // 12: looprpc.PushStaticAddressHtlcSigsRequest
	(*ClientHtlcSigningInfo)(nil),                  // 13: looprpc.ClientHtlcSigningInfo
	(*PushStaticAddressHtlcSigsResponse)(nil),      // 14: looprpc.PushStaticAddressHtlcSigsResponse
	(*PushStaticAddressSweeplessSigsRequest)(nil),  // 15: looprpc.PushStaticAddressSweeplessSigsRequest
	(*ClientSweeplessSigningInfo)(nil),             // 16: looprpc.ClientSweeplessSigningInfo
	(*PushStaticAddressSweeplessSigsResponse)(nil), // 17: looprpc.PushStaticAddressSweeplessSigsResponse
	nil,                 // 18: looprpc.ServerPsbtWithdrawRequest.DepositToNoncesEntry
	nil,                 // 19: looprpc.ServerPsbtWithdrawResponse.SigningInfoEntry
	nil,                 // 20: looprpc.PushStaticAddressSweeplessSigsRequest.SigningInfoEntry
	(*PrevoutInfo)(nil), // 21: looprpc.PrevoutInfo
}
var file_staticaddr_proto_depIdxs = []int32{
	0,  // 0: looprpc.ServerNewAddressRequest.protocol_version:type_name -> looprpc.StaticAddressProtocolVersion
	3,  // 1: looprpc.ServerNewAddressResponse.params:type_name -> looprpc.ServerAddressParameters
	21, // 2: looprpc.ServerWithdrawRequest.outpoints:type_name -> looprpc.PrevoutInfo
	18, // 3: looprpc.ServerPsbtWithdrawRequest.deposit_to_nonces:type_name -> looprpc.ServerPsbtWithdrawRequest.DepositToNoncesEntry
	19, // 4: looprpc.ServerPsbtWithdrawResponse.signing_info:type_name -> looprpc.ServerPsbtWithdrawResponse.SigningInfoEntry
	0,  // 5: looprpc.ServerStaticAddressLoopInRequest.protocol_version:type_name -> looprpc.StaticAddressProtocolVersion
	11, // 6: looprpc.ServerStaticAddressLoopInResponse.standard_htlc_info:type_name -> looprpc.ServerHtlcSigningInfo
	11, // 7: looprpc.ServerStaticAddressLoopInResponse.high_fee_htlc_info:type_name -> looprpc.ServerHtlcSigningInfo
	11, // 8: looprpc.ServerStaticAddressLoopInResponse.extreme_fee_htlc_info:type_name -> looprpc.ServerHtlcSigningInfo
	13, // 9: looprpc.PushStaticAddressHtlcSigsRequest.standard_htlc_info:type_name -> looprpc.ClientHtlcSigningInfo
	13, // 10: looprpc.PushStaticAddressHtlcSigsRequest.high_fee_htlc_info:type_name -> looprpc.ClientHtlcSigningInfo
	13, // 11: looprpc.PushStaticAddressHtlcSigsRequest.extreme_fee_htlc_info:type_name -> looprpc.ClientHtlcSigningInfo
	20, // 12: looprpc.PushStaticAddressSweeplessSigsRequest.signing_info:type_name -> looprpc.PushStaticAddressSweeplessSigsRequest.SigningInfoEntry
	8,  // 13: looprpc.ServerPsbtWithdrawResponse.SigningInfoEntry.value:type_name -> looprpc.ServerPsbtWithdrawSigningInfo
	16, // 14: looprpc.PushStaticAddressSweeplessSigsRequest.SigningInfoEntry.value:type_name -> looprpc.ClientSweeplessSigningInfo
	1,  // 15: looprpc.StaticAddressServer.ServerNewAddress:input_type -> looprpc.ServerNewAddressRequest
	4,  // 16: looprpc.StaticAddressServer.ServerWithdrawDeposits:input_type -> looprpc.ServerWithdrawRequest
	6,  // 17: looprpc.StaticAddressServer.ServerPsbtWithdrawDeposits:input_type -> looprpc.ServerPsbtWithdrawRequest
	9,  // 18: looprpc.StaticAddressServer.ServerStaticAddressLoopIn:input_type -> looprpc.ServerStaticAddressLoopInRequest
	12, // 19: looprpc.StaticAddressServer.PushStaticAddressHtlcSigs:input_type -> looprpc.PushStaticAddressHtlcSigsRequest
	15, // 20: looprpc.StaticAddressServer.PushStaticAddressSweeplessSigs:input_type -> looprpc.PushStaticAddressSweeplessSigsRequest
	2,  // 21: looprpc.StaticAddressServer.ServerNewAddress:output_type -> looprpc.ServerNewAddressResponse
	5,  // 22: looprpc.StaticAddressServer.ServerWithdrawDeposits:output_type -> looprpc.ServerWithdrawResponse
	7,  // 23: looprpc.StaticAddressServer.ServerPsbtWithdrawDeposits:output_type -> looprpc.ServerPsbtWithdrawResponse
	10, // 24: looprpc.StaticAddressServer.ServerStaticAddressLoopIn:output_type -> looprpc.ServerStaticAddressLoopInResponse
	14, // 25: looprpc.StaticAddressServer.PushStaticAddressHtlcSigs:output_type -> looprpc.PushStaticAddressHtlcSigsResponse
	17, // 26: looprpc.StaticAddressServer.PushStaticAddressSweeplessSigs:output_type -> looprpc.PushStaticAddressSweeplessSigsResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_staticaddr_proto_init() }
func file_staticaddr_proto_init() {
	if File_staticaddr_proto != nil {
		return
	}
	file_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staticaddr_proto_rawDesc), len(file_staticaddr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_staticaddr_proto_goTypes,
		DependencyIndexes: file_staticaddr_proto_depIdxs,
		EnumInfos:         file_staticaddr_proto_enumTypes,
		MessageInfos:      file_staticaddr_proto_msgTypes,
	}.Build()
	File_staticaddr_proto = out.File
	file_staticaddr_proto_goTypes = nil
	file_staticaddr_proto_depIdxs = nil
}
