package loopin

import (
	"bytes"
	"context"
	"database/sql"

	"github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/btcutil"
	"github.com/btcsuite/btcd/chaincfg"
	"github.com/btcsuite/btcd/wire"
	"github.com/lightninglabs/loop/fsm"
	"github.com/lightninglabs/loop/loopdb"
	"github.com/lightninglabs/loop/loopdb/sqlc"
	"github.com/lightninglabs/loop/staticaddr/version"
	"github.com/lightningnetwork/lnd/clock"
	"github.com/lightningnetwork/lnd/keychain"
	"github.com/lightningnetwork/lnd/lntypes"
	"github.com/lightningnetwork/lnd/lnwallet/chainfee"
)

const outpointSeparator = ";"

// Querier is the interface that contains all the queries generated by sqlc for
// the static_address_swaps table.
type Querier interface {
	// InsertSwap inserts a new base swap.
	InsertSwap(ctx context.Context, arg sqlc.InsertSwapParams) error

	// InsertHtlcKeys inserts the htlc keys for a swap.
	InsertHtlcKeys(ctx context.Context, arg sqlc.InsertHtlcKeysParams) error

	// InsertStaticAddressLoopIn inserts a new static address loop-in swap.
	InsertStaticAddressLoopIn(ctx context.Context,
		arg sqlc.InsertStaticAddressLoopInParams) error

	// InsertStaticAddressMetaUpdate inserts metadata about loop-in
	// updates.
	InsertStaticAddressMetaUpdate(ctx context.Context,
		arg sqlc.InsertStaticAddressMetaUpdateParams) error

	// UpdateStaticAddressLoopIn updates a loop-in swap.
	UpdateStaticAddressLoopIn(ctx context.Context,
		arg sqlc.UpdateStaticAddressLoopInParams) error

	// GetStaticAddressLoopInSwap retrieves a loop-in swap by its swap hash.
	GetStaticAddressLoopInSwap(ctx context.Context,
		swapHash []byte) (sqlc.GetStaticAddressLoopInSwapRow, error)

	// GetStaticAddressLoopInSwaps retrieves all loop-in swaps.
	GetStaticAddressLoopInSwaps(ctx context.Context) (
		[]sqlc.GetStaticAddressLoopInSwapsRow, error)

	// GetLoopInSwapUpdates retrieves all updates for a loop-in swap.
	GetLoopInSwapUpdates(ctx context.Context,
		swapHash []byte) ([]sqlc.StaticAddressSwapUpdate, error)
}

// BaseDB is the interface that contains all the queries generated by sqlc for
// the static_address_swaps table and transaction functionality.
type BaseDB interface {
	Querier

	// ExecTx allows for executing a function in the context of a database
	// transaction.
	ExecTx(ctx context.Context, txOptions loopdb.TxOptions,
		txBody func(Querier) error) error
}

// SqlStore is the backing store for static address loop-ins.
type SqlStore struct {
	baseDB  BaseDB
	clock   clock.Clock
	network *chaincfg.Params
}

// NewSqlStore constructs a new SQLStore from a BaseDB. The BaseDB is agnostic
// to the underlying driver which can be postgres or sqlite.
func NewSqlStore(db BaseDB, clock clock.Clock,
	network *chaincfg.Params) *SqlStore {

	return &SqlStore{
		baseDB:  db,
		clock:   clock,
		network: network,
	}
}

// AllLoopIns retrieves all known loop-ins from the database.
func (s *SqlStore) AllLoopIns(ctx context.Context) ([]*StaticAddressLoopIn,
	error) {

	rows, err := s.baseDB.GetStaticAddressLoopInSwaps(ctx)
	if err != nil {
		return nil, err
	}

	var loopIns []*StaticAddressLoopIn
	for _, row := range rows {
		updates, err := s.baseDB.GetLoopInSwapUpdates(
			ctx, row.SwapHash,
		)
		if err != nil {
			return nil, err
		}

		loopIn, err := toStaticAddressLoopIn(
			ctx, s.network, sqlc.GetStaticAddressLoopInSwapRow(row),
			updates,
		)
		if err != nil {
			return nil, err
		}

		loopIns = append(loopIns, loopIn)
	}

	return loopIns, nil
}

// CreateLoopIn inserts a new loop-in swap into the database. Basic loop-in
// parameters are stored in the swaps table, htlc key information is stored in
// the htlc_keys table, and loop-in specific information is stored in the
// static_address_swaps table.
func (s *SqlStore) CreateLoopIn(ctx context.Context,
	loopIn *StaticAddressLoopIn) error {

	swapArgs := sqlc.InsertSwapParams{
		SwapHash:         loopIn.SwapHash[:],
		Preimage:         loopIn.SwapPreimage[:],
		InitiationTime:   s.clock.Now(),
		AmountRequested:  int64(loopIn.TotalDepositAmount()),
		CltvExpiry:       loopIn.HtlcCltvExpiry,
		MaxSwapFee:       int64(loopIn.MaxSwapFee),
		InitiationHeight: int32(loopIn.InitiationHeight),
		ProtocolVersion:  int32(loopIn.ProtocolVersion),
		Label:            loopIn.Label,
	}

	htlcKeyArgs := sqlc.InsertHtlcKeysParams{
		SwapHash:             loopIn.SwapHash[:],
		SenderScriptPubkey:   loopIn.ClientPubkey.SerializeCompressed(),
		ReceiverScriptPubkey: loopIn.ServerPubkey.SerializeCompressed(),
		ClientKeyFamily:      int32(loopIn.HtlcKeyLocator.Family),
		ClientKeyIndex:       int32(loopIn.HtlcKeyLocator.Index),
	}

	depositOutpointByteSlice := depositOutpointsToByteSlice(
		loopIn.DepositOutpoints,
	)
	staticAddressLoopInParams := sqlc.InsertStaticAddressLoopInParams{
		SwapHash:         loopIn.SwapHash[:],
		SwapInvoice:      loopIn.SwapInvoice,
		LastHop:          loopIn.LastHop,
		QuotedSwapFee:    int64(loopIn.QuotedSwapFee),
		DepositOutpoints: depositOutpointByteSlice,
	}

	updateArgs := sqlc.InsertStaticAddressMetaUpdateParams{
		SwapHash:        loopIn.SwapHash[:],
		UpdateTimestamp: s.clock.Now(),
		UpdateState:     string(loopIn.GetState()),
	}

	return s.baseDB.ExecTx(ctx, loopdb.NewSqlWriteOpts(),
		func(q Querier) error {
			err := q.InsertSwap(ctx, swapArgs)
			if err != nil {
				return err
			}

			err = q.InsertHtlcKeys(ctx, htlcKeyArgs)
			if err != nil {
				return err
			}

			err = q.InsertStaticAddressLoopIn(
				ctx, staticAddressLoopInParams,
			)
			if err != nil {
				return err
			}

			return q.InsertStaticAddressMetaUpdate(ctx, updateArgs)
		})
}

// UpdateLoopIn updates the loop-in in the database.
func (s *SqlStore) UpdateLoopIn(ctx context.Context,
	loopIn *StaticAddressLoopIn) error {

	var htlcTx []byte
	if loopIn.HtlcTx != nil {
		var buffer bytes.Buffer
		err := loopIn.HtlcTx.Serialize(
			&buffer,
		)
		if err != nil {
			return err
		}
		htlcTx = buffer.Bytes()
	}

	var htlcTimeoutSweepTx []byte
	if loopIn.HtlcTimeoutSweepTx != nil {
		var buffer bytes.Buffer
		err := loopIn.HtlcTimeoutSweepTx.Serialize(
			&buffer,
		)
		if err != nil {
			return err
		}
		htlcTimeoutSweepTx = buffer.Bytes()
	}

	var htlcTimeoutSweepAddress sql.NullString
	if loopIn.HtlcTimeoutSweepAddress != nil {
		htlcTimeoutSweepAddress = sql.NullString{
			String: loopIn.HtlcTimeoutSweepAddress.String(),
			Valid:  loopIn.HtlcTimeoutSweepAddress.String() != "",
		}
	}

	updateParams := sqlc.UpdateStaticAddressLoopInParams{
		SwapHash:                loopIn.SwapHash[:],
		HtlcTx:                  htlcTx,
		HtlcTxFeeRate:           int64(loopIn.HtlcTxFeeRate),
		HtlcTimeoutSweepTx:      htlcTimeoutSweepTx,
		HtlcTimeoutSweepAddress: htlcTimeoutSweepAddress,
	}

	updateArgs := sqlc.InsertStaticAddressMetaUpdateParams{
		SwapHash:        loopIn.SwapHash[:],
		UpdateState:     string(loopIn.GetState()),
		UpdateTimestamp: s.clock.Now(),
	}

	return s.baseDB.ExecTx(ctx, loopdb.NewSqlWriteOpts(),
		func(q Querier) error {
			err := q.UpdateStaticAddressLoopIn(ctx, updateParams)
			if err != nil {
				return err
			}

			return q.InsertStaticAddressMetaUpdate(ctx, updateArgs)
		},
	)
}

// depositOutpointsToByteSlice converts a slice of deposit outpoints to a byte
// slice.
func depositOutpointsToByteSlice(outpoints []string) []byte {
	var slice []byte
	for _, o := range outpoints {
		slice = append(slice, []byte(o)...)
		slice = append(slice, []byte(outpointSeparator)...)
	}

	return slice
}

// toStaticAddressLoopIn converts sql rows to an instant out struct.
func toStaticAddressLoopIn(_ context.Context, network *chaincfg.Params,
	row sqlc.GetStaticAddressLoopInSwapRow,
	updates []sqlc.StaticAddressSwapUpdate) (*StaticAddressLoopIn, error) {

	swapHash, err := lntypes.MakeHash(row.SwapHash)
	if err != nil {
		return nil, err
	}

	swapPreImage, err := lntypes.MakePreimage(row.Preimage)
	if err != nil {
		return nil, err
	}

	clientKey, err := btcec.ParsePubKey(row.SenderScriptPubkey)
	if err != nil {
		return nil, err
	}

	serverKey, err := btcec.ParsePubKey(row.ReceiverScriptPubkey)
	if err != nil {
		return nil, err
	}

	var htlcTx *wire.MsgTx
	if row.HtlcTx != nil {
		htlcTx = &wire.MsgTx{}
		err = htlcTx.Deserialize(bytes.NewReader(row.HtlcTx))
		if err != nil {
			return nil, err
		}
	}

	var htlcTimeoutSweepTx *wire.MsgTx
	if row.HtlcTimeoutSweepTx != nil {
		htlcTimeoutSweepTx = &wire.MsgTx{}
		err := htlcTimeoutSweepTx.Deserialize(bytes.NewReader(
			row.HtlcTimeoutSweepTx,
		))
		if err != nil {
			return nil, err
		}
	}

	depositOutpoints := byteSliceToDepositOutpoints(row.DepositOutpoints)
	if err != nil {
		return nil, err
	}

	timeoutAddressString := row.HtlcTimeoutSweepAddress.String
	var timeoutAddress btcutil.Address
	if timeoutAddressString != "" {
		timeoutAddress, err = btcutil.DecodeAddress(
			timeoutAddressString, network,
		)
		if err != nil {
			return nil, err
		}
	}

	loopIn := &StaticAddressLoopIn{
		SwapHash:         swapHash,
		SwapPreimage:     swapPreImage,
		HtlcCltvExpiry:   row.CltvExpiry,
		MaxSwapFee:       btcutil.Amount(row.MaxSwapFee),
		InitiationHeight: uint32(row.InitiationHeight),
		ProtocolVersion: version.AddressProtocolVersion(
			row.ProtocolVersion,
		),
		Label:        row.Label,
		ClientPubkey: clientKey,
		ServerPubkey: serverKey,
		HtlcKeyLocator: keychain.KeyLocator{
			Family: keychain.KeyFamily(row.ClientKeyFamily),
			Index:  uint32(row.ClientKeyIndex),
		},
		SwapInvoice:      row.SwapInvoice,
		LastHop:          row.LastHop,
		QuotedSwapFee:    btcutil.Amount(row.QuotedSwapFee),
		DepositOutpoints: depositOutpoints,
		HtlcTxFeeRate: chainfee.SatPerKWeight(
			row.HtlcTxFeeRate,
		),
		HtlcTimeoutSweepAddress: timeoutAddress,
		HtlcTx:                  htlcTx,
		HtlcTimeoutSweepTx:      htlcTimeoutSweepTx,
	}

	if len(updates) > 0 {
		lastUpdate := updates[len(updates)-1]
		loopIn.SetState(fsm.StateType(lastUpdate.UpdateState))
	}

	return loopIn, nil
}

func byteSliceToDepositOutpoints(byteSlice []byte) []string {
	var outpoints []string
	outpointBytes := bytes.Split(byteSlice, []byte(outpointSeparator))
	for _, o := range outpointBytes {
		outpoint := string(o)
		if outpoint != "" {
			outpoints = append(outpoints, outpoint)
		}
	}

	return outpoints
}
