name: Release Notes

on:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  release-notes:
    name: Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check release notes
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          NO_CHANGELOG: ${{ contains(github.event.pull_request.labels.*.name, 'no-changelog') }}
        run: scripts/release-notes.py pr "$BASE_SHA" "$HEAD_SHA"
